name: Unit_Tests 

on: [push, pull_request]

jobs:
  Dynamic_Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: sudo apt-get install -y g++ libgtest-dev 

      - name: Build and run unit tests 
        working-directory: backend/unit_tests
        run: |
          g++ -std=c++14 *.cpp ../src/map.cpp ../src/aircraft.cpp -lgtest_main -lgtest -Isrc/.
          ./a.out
