name: Unit_Tests 

on: [push, pull_request]

jobs:
  Static_Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: sudo apt-get install -y g++ libgtest-dev 

      - name: Build and run unit tests 
        run: |
          cd unit_tests
          g++ -std=c++14 GridMapTester.cpp ../src/*.cpp -lgtest_main -lgtest -Isrc/.
          ./a.out
